// Каталог фильтров. Каждая опция имеет labelRu + promptText (англ., идёт в промт).

window.FILTERS = {
  referenceTypes: {
    label: 'Тип референса',
    hint: 'Что подаем на вход',
    required: true,
    multi: true,
    kind: 'chips',
    options: [
      { id: 'product', labelRu: 'Товар', promptText: null },
      { id: 'model', labelRu: 'Модель', promptText: null },
    ],
  },
  productPhotoCount: {
    label: 'Количество фото продукта',
    required: true,
    kind: 'chips',
    options: [
      { id: '1', labelRu: '1', promptText: '1' },
      { id: '2', labelRu: '2', promptText: '2' },
      { id: '3', labelRu: '3', promptText: '3' },
      { id: '4', labelRu: '4', promptText: '4' },
      { id: '5', labelRu: '5', promptText: '5' },
      { id: '6', labelRu: '6', promptText: '6' },
    ],
  },
  modelPhotoCount: {
    label: 'Количество фото модели',
    required: true,
    kind: 'chips',
    options: [
      { id: '1', labelRu: '1', promptText: '1' },
      { id: '2', labelRu: '2', promptText: '2' },
      { id: '3', labelRu: '3', promptText: '3' },
      { id: '4', labelRu: '4', promptText: '4' },
      { id: '5', labelRu: '5', promptText: '5' },
      { id: '6', labelRu: '6', promptText: '6' },
    ],
  },
  gender: {
    label: 'Пол модели',
    required: true,
    kind: 'chips',
    options: [
      { id: 'male', labelRu: 'Мужчина', promptText: 'man' },
      { id: 'female', labelRu: 'Женщина', promptText: 'woman' },
      { id: 'from_reference', labelRu: 'С референса', promptText: null },
    ],
  },
  ageGroup: {
    label: 'Возраст',
    required: true,
    kind: 'chips',
    options: [
      { id: 'teen', labelRu: 'Подросток', sub: '16–19', promptText: 'a teenager (16–19 years old)' },
      { id: 'young', labelRu: 'Молодой', sub: '20–29', promptText: 'a young adult (20–29 years old)' },
      { id: 'adult', labelRu: 'Взрослый', sub: '30–45', promptText: 'an adult (30–45 years old)' },
      { id: 'mature', labelRu: 'Зрелый', sub: '45–60', promptText: 'a mature adult (45–60 years old)' },
      { id: 'senior', labelRu: 'Пожилой', sub: '60+', promptText: 'a senior (60+ years old)' },
    ],
  },
  ethnicity: {
    label: 'Тип внешности',
    optional: true,
    kind: 'grid',
    options: [
      { id: 'slavic', labelRu: 'Славянская', promptText: 'slavic' },
      { id: 'european', labelRu: 'Западноевропейская', promptText: 'european' },
      { id: 'scandinavian', labelRu: 'Скандинавская', promptText: 'scandinavian' },
      { id: 'mediterranean', labelRu: 'Средиземноморская', promptText: 'mediterranean' },
      { id: 'asian_east', labelRu: 'Восточноазиатская', promptText: 'east asian' },
      { id: 'asian_central', labelRu: 'Центральноазиатская', promptText: 'central asian' },
      { id: 'south_asian', labelRu: 'Южноазиатская', promptText: 'south asian' },
      { id: 'african', labelRu: 'Африканская', promptText: 'african' },
      { id: 'latino', labelRu: 'Латиноамериканская', promptText: 'latino' },
      { id: 'middle_eastern', labelRu: 'Ближневосточная', promptText: 'middle eastern' },
      { id: 'mixed', labelRu: 'Смешанная', promptText: 'mixed-race' },
    ],
  },
  skinColor: {
    label: 'Цвет кожи',
    optional: true,
    kind: 'grid',
    options: [
      { id: 'porcelain',   labelRu: 'Фарфоровый',       promptText: 'porcelain skin',         swatch: '#f5e4d2' },
      { id: 'fair',        labelRu: 'Светлый',           promptText: 'fair skin',               swatch: '#f0ceaa' },
      { id: 'light',       labelRu: 'Светло-бежевый',   promptText: 'light beige skin',        swatch: '#e8b98a' },
      { id: 'beige',       labelRu: 'Бежевый',           promptText: 'warm beige skin',         swatch: '#d4a06a' },
      { id: 'olive',       labelRu: 'Оливковый',         promptText: 'olive skin',              swatch: '#c08050' },
      { id: 'tan',         labelRu: 'Загорелый',         promptText: 'tan skin',                swatch: '#a86838' },
      { id: 'brown',       labelRu: 'Коричневый',        promptText: 'medium brown skin',       swatch: '#7a4a28' },
      { id: 'dark_brown',  labelRu: 'Тёмно-коричневый', promptText: 'deep brown skin',         swatch: '#4a2810' },
      { id: 'deep',        labelRu: 'Тёмный',            promptText: 'very deep dark skin',     swatch: '#2a1408' },
    ],
  },
  eyeColor: {
    label: 'Цвет глаз',
    optional: true,
    kind: 'grid',
    options: [
      { id: 'brown',       labelRu: 'Карие',             promptText: 'brown eyes',              swatch: '#6b4220' },
      { id: 'dark_brown',  labelRu: 'Тёмно-карие',      promptText: 'dark brown eyes',         swatch: '#2e1508' },
      { id: 'hazel',       labelRu: 'Ореховые',          promptText: 'hazel eyes',              swatch: '#7a6030' },
      { id: 'amber',       labelRu: 'Янтарные',          promptText: 'amber eyes',              swatch: '#c08820' },
      { id: 'green',       labelRu: 'Зелёные',           promptText: 'green eyes',              swatch: '#3a7040' },
      { id: 'blue',        labelRu: 'Голубые',           promptText: 'blue eyes',               swatch: '#3a68a8' },
      { id: 'grey',        labelRu: 'Серые',             promptText: 'grey eyes',               swatch: '#6a7a88' },
      { id: 'black',       labelRu: 'Тёмные',            promptText: 'dark nearly-black eyes',  swatch: '#1a1008' },
    ],
  },
  bodyType: {
    label: 'Телосложение',
    optional: true,
    kind: 'chips',
    options: [
      { id: 'slim', labelRu: 'Стройное', promptText: 'slim build' },
      { id: 'athletic', labelRu: 'Атлетичное', promptText: 'athletic build' },
      { id: 'average', labelRu: 'Среднее', promptText: 'average build' },
      { id: 'curvy', labelRu: 'С изгибами', promptText: 'curvy build', onlyGender: 'female' },
      { id: 'muscular', labelRu: 'Мускулистое', promptText: 'muscular build', onlyGender: 'male' },
      { id: 'plus_size', labelRu: 'Plus-size', promptText: 'plus-size' },
    ],
  },
  hairLength: {
    label: 'Длина волос',
    optional: true,
    kind: 'chips',
    options: [
      { id: 'bald', labelRu: 'Бритый налысо', promptText: 'shaved head' },
      { id: 'very_short', labelRu: 'Очень короткие', promptText: 'very short hair' },
      { id: 'short', labelRu: 'Короткие', promptText: 'short hair' },
      { id: 'medium', labelRu: 'Средние', sub: 'до плеч', promptText: 'medium-length hair' },
      { id: 'long', labelRu: 'Длинные', promptText: 'long hair' },
      { id: 'very_long', labelRu: 'Очень длинные', promptText: 'very long hair' },
    ],
  },
  hairColor: {
    label: 'Цвет волос',
    required: true,
    kind: 'grid',
    options: [
      { id: 'black', labelRu: 'Чёрный', promptText: 'black', swatch: '#1a1a1a' },
      { id: 'dark_brown', labelRu: 'Тёмно-каштановый', promptText: 'dark brown', swatch: '#3b2416' },
      { id: 'brown', labelRu: 'Каштановый', promptText: 'brown', swatch: '#6b4423' },
      { id: 'light_brown', labelRu: 'Светло-русый', promptText: 'light brown', swatch: '#a67c52' },
      { id: 'blonde', labelRu: 'Блонд', promptText: 'blonde', swatch: '#d9b382' },
      { id: 'platinum', labelRu: 'Платиновый', promptText: 'platinum blonde', swatch: '#ebe2cf' },
      { id: 'red', labelRu: 'Рыжий', promptText: 'red', swatch: '#a04524' },
      { id: 'grey', labelRu: 'Седой', promptText: 'grey', swatch: '#9a9a95' },
      { id: 'white', labelRu: 'Белый', promptText: 'white', swatch: '#f0eee6' },
      { id: 'dyed_unusual', labelRu: 'Крашеный яркий', promptText: 'unnaturally dyed', swatch: 'linear-gradient(135deg,#b85c3c,#4a5240)' },
    ],
  },
  facialHair: {
    label: 'Борода и усы',
    optional: true,
    kind: 'chips',
    options: [
      { id: 'clean_shaven', labelRu: 'Гладко выбрит', promptText: 'clean-shaven' },
      { id: 'stubble', labelRu: 'Щетина', promptText: 'light stubble' },
      { id: 'short_beard', labelRu: 'Короткая борода', promptText: 'a short beard' },
      { id: 'full_beard', labelRu: 'Полная борода', promptText: 'a full beard' },
      { id: 'goatee', labelRu: 'Козлиная бородка', promptText: 'a goatee' },
      { id: 'mustache', labelRu: 'Только усы', promptText: 'a mustache only' },
    ],
  },
  features: {
    label: 'Особенности внешности',
    hint: 'Можно выбрать несколько',
    optional: true,
    multi: true,
    kind: 'chips',
    options: [
      { id: 'visible_tattoo', labelRu: 'Татуировки', promptText: 'visible tattoos' },
      { id: 'freckles', labelRu: 'Веснушки', promptText: 'freckles' },
      { id: 'moles', labelRu: 'Родинки', promptText: 'moles' },
      { id: 'glasses_optical', labelRu: 'Очки', promptText: 'glasses' },
      { id: 'glasses_sun', labelRu: 'Солнцезащитные очки', promptText: 'sunglasses' },
      { id: 'earrings', labelRu: 'Серьги', promptText: 'earrings' },
      { id: 'chain', labelRu: 'Цепочка / ожерелье', promptText: 'a chain necklace' },
      { id: 'rings', labelRu: 'Кольца', promptText: 'rings' },
      { id: 'bracelets', labelRu: 'Браслеты', promptText: 'bracelets' },
      { id: 'watch', labelRu: 'Наручные часы', promptText: 'a wristwatch' },
      { id: 'nose_piercing', labelRu: 'Пирсинг в носу', promptText: 'a nose piercing' },
      { id: 'bold_makeup', labelRu: 'Яркий макияж', promptText: 'bold makeup' },
      { id: 'natural_makeup', labelRu: 'Лёгкий макияж', promptText: 'natural makeup' },
      { id: 'long_nails', labelRu: 'Длинные ногти', promptText: 'long nails' },
    ],
  },
  featuresOverride: {
    label: 'Уточнение',
    hint: 'Можно внести правки',
    optional: true,
    kind: 'text',
    placeholder: 'например: visible tattoos, gold chain necklace',
  },

  productGender: {
    label: 'Кому товар',
    required: true,
    kind: 'chips',
    options: [
      { id: 'men', labelRu: 'Мужской', promptText: "men's" },
      { id: 'women', labelRu: 'Женский', promptText: "women's" },
      { id: 'unisex', labelRu: 'Унисекс', promptText: 'unisex' },
      { id: 'kids', labelRu: 'Детский', promptText: "kids'" },
    ],
  },
  productCategories: {
    label: 'Категория',
    hint: 'Можно выбрать несколько',
    required: true,
    kind: 'chips',
    multi: true,
    options: [
      { id: 'top', labelRu: 'Верх', promptText: null },
      { id: 'bottom', labelRu: 'Низ', promptText: null },
      { id: 'outerwear', labelRu: 'Верхняя одежда', promptText: null },
      { id: 'dress', labelRu: 'Платья / юбки', promptText: null, needsProductGender: ['women', 'kids', 'unisex'] },
      { id: 'full_outfit', labelRu: 'Комплект / костюм', promptText: null },
      { id: 'footwear', labelRu: 'Обувь', promptText: null },
      { id: 'accessory', labelRu: 'Аксессуар', promptText: null },
    ],
  },
  productSub: {
    label: 'Тип изделия',
    required: true,
    kind: 'grid',
    dependsOn: 'productCategory',
    byParent: {
      top: [
        { id: 'tshirt', labelRu: 'Футболка', promptText: 't-shirt' },
        { id: 'polo', labelRu: 'Поло', promptText: 'polo shirt' },
        { id: 'shirt', labelRu: 'Рубашка', promptText: 'button-up shirt' },
        { id: 'longsleeve', labelRu: 'Лонгслив', promptText: 'long-sleeve shirt' },
        { id: 'sweater', labelRu: 'Свитер', promptText: 'sweater' },
        { id: 'hoodie', labelRu: 'Худи', promptText: 'hoodie' },
        { id: 'sweatshirt', labelRu: 'Свитшот', promptText: 'sweatshirt' },
        { id: 'tanktop', labelRu: 'Майка', promptText: 'tank top' },
      ],
      bottom: [
        { id: 'jeans', labelRu: 'Джинсы', promptText: 'jeans' },
        { id: 'trousers', labelRu: 'Брюки', promptText: 'trousers' },
        { id: 'shorts', labelRu: 'Шорты', promptText: 'shorts' },
        { id: 'joggers', labelRu: 'Джоггеры', promptText: 'joggers' },
        { id: 'skirt', labelRu: 'Юбка', promptText: 'skirt' },
        { id: 'leggings', labelRu: 'Легинсы', promptText: 'leggings' },
      ],
      outerwear: [
        { id: 'jacket', labelRu: 'Куртка', promptText: 'jacket' },
        { id: 'coat', labelRu: 'Пальто', promptText: 'coat' },
        { id: 'parka', labelRu: 'Парка', promptText: 'parka' },
        { id: 'trench', labelRu: 'Тренч', promptText: 'trench coat' },
        { id: 'blazer', labelRu: 'Пиджак', promptText: 'blazer' },
        { id: 'bomber', labelRu: 'Бомбер', promptText: 'bomber jacket' },
        { id: 'windbreaker', labelRu: 'Ветровка', promptText: 'windbreaker' },
      ],
      dress: [
        { id: 'mini_dress', labelRu: 'Мини-платье', promptText: 'mini dress' },
        { id: 'midi_dress', labelRu: 'Миди-платье', promptText: 'midi dress' },
        { id: 'maxi_dress', labelRu: 'Макси-платье', promptText: 'maxi dress' },
        { id: 'summer_dress', labelRu: 'Летнее платье', promptText: 'summer dress' },
        { id: 'evening_dress', labelRu: 'Вечернее платье', promptText: 'evening dress' },
      ],
      full_outfit: [
        { id: 'suit', labelRu: 'Деловой костюм', promptText: 'suit', components: 'blazer and trousers' },
        { id: 'tracksuit', labelRu: 'Спортивный костюм', promptText: 'tracksuit', components: 'hoodie and joggers' },
        { id: 'cotton_set', labelRu: 'Хлопковый комплект', promptText: 'cotton outfit set', components: 't-shirt and pants' },
        { id: 'two_piece', labelRu: 'Комплект из двух предметов', promptText: 'two-piece outfit' },
        { id: 'jumpsuit', labelRu: 'Комбинезон', promptText: 'jumpsuit' },
      ],
      footwear: [
        { id: 'sneakers', labelRu: 'Кроссовки', promptText: 'sneakers' },
        { id: 'boots', labelRu: 'Ботинки', promptText: 'boots' },
        { id: 'loafers', labelRu: 'Лоферы', promptText: 'loafers' },
        { id: 'sandals', labelRu: 'Сандалии', promptText: 'sandals' },
        { id: 'heels', labelRu: 'Туфли на каблуке', promptText: 'heels' },
        { id: 'flats', labelRu: 'Балетки', promptText: 'flats' },
        { id: 'dress_shoes', labelRu: 'Классические туфли', promptText: 'dress shoes' },
      ],
      accessory: [
        { id: 'bag', labelRu: 'Сумка', promptText: 'bag' },
        { id: 'belt', labelRu: 'Ремень', promptText: 'belt' },
        { id: 'hat', labelRu: 'Шляпа', promptText: 'hat' },
        { id: 'scarf', labelRu: 'Шарф', promptText: 'scarf' },
        { id: 'gloves', labelRu: 'Перчатки', promptText: 'gloves' },
        { id: 'cap', labelRu: 'Кепка', promptText: 'cap' },
        { id: 'backpack', labelRu: 'Рюкзак', promptText: 'backpack' },
      ],
    },
  },
  productColor: {
    label: 'Цвет',
    required: true,
    kind: 'swatches',
    options: [
      { id: 'black', labelRu: 'Чёрный', promptText: 'black', swatch: '#1a1a1a' },
      { id: 'white', labelRu: 'Белый', promptText: 'white', swatch: '#ffffff' },
      { id: 'off_white', labelRu: 'Молочный', promptText: 'off-white', swatch: '#f2ede2' },
      { id: 'beige', labelRu: 'Бежевый', promptText: 'beige', swatch: '#d9c7a7' },
      { id: 'grey', labelRu: 'Серый', promptText: 'grey', swatch: '#9a9a95' },
      { id: 'navy', labelRu: 'Тёмно-синий', promptText: 'navy', swatch: '#1b2a4a' },
      { id: 'blue', labelRu: 'Синий', promptText: 'blue', swatch: '#2a5aa8' },
      { id: 'light_blue', labelRu: 'Голубой', promptText: 'light blue', swatch: '#a8c8e0' },
      { id: 'green', labelRu: 'Зелёный', promptText: 'green', swatch: '#2f6d3e' },
      { id: 'olive', labelRu: 'Оливковый', promptText: 'olive', swatch: '#4a5240' },
      { id: 'khaki', labelRu: 'Хаки', promptText: 'khaki', swatch: '#8c7a4f' },
      { id: 'brown', labelRu: 'Коричневый', promptText: 'brown', swatch: '#5a3a23' },
      { id: 'red', labelRu: 'Красный', promptText: 'red', swatch: '#a3272a' },
      { id: 'burgundy', labelRu: 'Бордовый', promptText: 'burgundy', swatch: '#5a1a22' },
      { id: 'pink', labelRu: 'Розовый', promptText: 'pink', swatch: '#e0aec0' },
      { id: 'yellow', labelRu: 'Жёлтый', promptText: 'yellow', swatch: '#e0c060' },
      { id: 'multicolor', labelRu: 'Мультицвет', promptText: 'multicolor', swatch: 'conic-gradient(from 0deg, #a3272a,#e0c060,#2f6d3e,#2a5aa8,#a3272a)' },
      { id: 'patterned', labelRu: 'С принтом', promptText: 'patterned', swatch: 'repeating-linear-gradient(45deg,#1a1a1a 0 4px,#f2ede2 4px 8px)' },
    ],
  },
  productMaterial: {
    label: 'Материал',
    optional: true,
    kind: 'grid',
    options: [
      { id: 'cotton', labelRu: 'Хлопок', promptText: 'cotton' },
      { id: 'linen', labelRu: 'Лён', promptText: 'linen' },
      { id: 'wool', labelRu: 'Шерсть', promptText: 'wool' },
      { id: 'cashmere', labelRu: 'Кашемир', promptText: 'cashmere' },
      { id: 'silk', labelRu: 'Шёлк', promptText: 'silk' },
      { id: 'denim', labelRu: 'Деним', promptText: 'denim' },
      { id: 'leather', labelRu: 'Кожа', promptText: 'leather' },
      { id: 'suede', labelRu: 'Замша', promptText: 'suede' },
      { id: 'knit', labelRu: 'Трикотаж', promptText: 'knit' },
      { id: 'fleece', labelRu: 'Флис', promptText: 'fleece' },
      { id: 'nylon', labelRu: 'Нейлон', promptText: 'nylon' },
      { id: 'polyester', labelRu: 'Полиэстер', promptText: 'polyester' },
    ],
  },
  productDetails: {
    label: 'Своё уточнение',
    hint: 'Попадёт в скобках в конец PRODUCT',
    optional: true,
    kind: 'text',
    placeholder: 'например: oversized fit',
  },

  fitNotes: {
    label: 'Посадка и подача',
    optional: true,
    multi: true,
    kind: 'chips',
    options: [
      { id: 'tucked_in', labelRu: 'Верх заправлен', promptText: 'top tucked in' },
      { id: 'sleeves_rolled', labelRu: 'Рукава закатаны', promptText: 'sleeves rolled up' },
      { id: 'buttoned_up', labelRu: 'Застёгнуто полностью', promptText: 'fully buttoned' },
      { id: 'unbuttoned', labelRu: 'Расстёгнуто', promptText: 'unbuttoned casually' },
      { id: 'open_jacket', labelRu: 'Куртка нараспашку', promptText: 'jacket worn open' },
      { id: 'layered', labelRu: 'Со слоями', promptText: 'styled with layering' },
      { id: 'oversized_look', labelRu: 'Оверсайз-посадка', promptText: 'oversized styling' },
      { id: 'fitted_look', labelRu: 'Облегающая', promptText: 'fitted silhouette' },
    ],
  },
  supportingItems: {
    label: 'Поддерживающие элементы',
    hint: 'Ненавязчивые дополнения к образу',
    optional: true,
    multi: true,
    kind: 'chips',
    options: [
      { id: 'minimal_sneakers', labelRu: 'Минималистичные кроссовки', promptText: 'minimal white sneakers' },
      { id: 'leather_boots', labelRu: 'Кожаные ботинки', promptText: 'plain leather boots' },
      { id: 'dress_shoes', labelRu: 'Классические туфли', promptText: 'simple dress shoes' },
      { id: 'neutral_bag', labelRu: 'Нейтральная сумка', promptText: 'a minimal unbranded bag' },
      { id: 'thin_belt', labelRu: 'Тонкий ремень', promptText: 'a thin leather belt' },
      { id: 'simple_cap', labelRu: 'Простая кепка', promptText: 'a plain cap' },
      { id: 'scarf', labelRu: 'Шарф', promptText: 'a neutral scarf' },
    ],
  },
  customStyling: {
    label: 'Кастомная инструкция стайлинга',
    hint: 'Одна строка на английском',
    optional: true,
    kind: 'text',
    placeholder: 'например: shirt slightly oversized on the shoulders',
  },

  moodReference: {
    label: 'Настроение',
    required: true,
    kind: 'grid',
    options: [
      { id: 'fashion_magazine', labelRu: 'Фэшн-журнал', promptText: 'fashion magazine editorial' },
      { id: 'minimalist_editorial', labelRu: 'Минимализм', promptText: 'clean minimalist aesthetic' },
      { id: 'luxury_editorial', labelRu: 'Люкс', promptText: 'high-end luxury style' },
      { id: 'streetwear', labelRu: 'Уличная мода', promptText: 'authentic streetwear' },
      { id: 'urban_casual', labelRu: 'Городская жизнь', promptText: 'urban casual lifestyle' },
      { id: 'cozy_lifestyle', labelRu: 'Уют', promptText: 'warm cozy lifestyle' },
      { id: 'scandinavian', labelRu: 'Скандинавский', promptText: 'scandinavian minimalism' },
      { id: 'mediterranean_summer', labelRu: 'Средиземноморье', promptText: 'mediterranean summer vibe' },
      { id: 'nordic_winter', labelRu: 'Нордическая зима', promptText: 'crisp nordic winter mood' },
      { id: 'y2k', labelRu: 'Y2K', promptText: 'y2k revival aesthetic' },
      { id: 'clean_catalog', labelRu: 'Чистый каталог', promptText: 'clean commercial catalog' },
      { id: 'cinematic', labelRu: 'Кинематографично', promptText: 'cinematic editorial' },
    ],
  },
  locationMode: {
    label: 'Локация',
    required: true,
    kind: 'chips',
    options: [
      { id: 'auto', labelRu: 'Автовыбор по настроению', promptText: null },
      { id: 'explicit', labelRu: 'Указать явно', promptText: null },
    ],
  },
  locationType: {
    label: 'Тип локации',
    required: true,
    kind: 'chips',
    options: [
      { id: 'studio', labelRu: 'Студия', promptText: null },
      { id: 'indoor', labelRu: 'В помещении', promptText: null },
      { id: 'outdoor_urban', labelRu: 'Городская среда', promptText: null },
      { id: 'outdoor_nature', labelRu: 'Природа', promptText: null },
    ],
  },
  locationSpecific: {
    label: 'Конкретная локация',
    required: true,
    kind: 'grid',
    dependsOn: 'locationType',
    byParent: {
      studio: [
        { id: 'white_cyclorama', labelRu: 'Белая циклорама', promptText: 'a clean white cyclorama studio' },
        { id: 'grey_seamless', labelRu: 'Серый seamless', promptText: 'a neutral grey seamless studio' },
        { id: 'beige_seamless', labelRu: 'Бежевый seamless', promptText: 'a warm beige seamless studio' },
        { id: 'black_seamless', labelRu: 'Чёрный seamless', promptText: 'a black seamless studio' },
        { id: 'textured_backdrop', labelRu: 'Бетонная фактура', promptText: 'a textured concrete studio backdrop' },
      ],
      indoor: [
        { id: 'minimalist_apartment', labelRu: 'Светлая квартира', promptText: 'a minimalist light-toned apartment interior' },
        { id: 'industrial_loft', labelRu: 'Индустриальный лофт', promptText: 'an industrial loft with brick and concrete' },
        { id: 'cozy_bedroom', labelRu: 'Уютная спальня', promptText: 'a cozy warm-lit bedroom' },
        { id: 'cafe_interior', labelRu: 'Стильное кафе', promptText: 'a stylish cafe interior' },
        { id: 'art_gallery', labelRu: 'Галерея', promptText: 'a modern art gallery with white walls' },
        { id: 'hotel_lobby', labelRu: 'Лобби отеля', promptText: 'a refined hotel lobby' },
        { id: 'staircase', labelRu: 'Бетонная лестница', promptText: 'a modernist concrete staircase' },
        { id: 'empty_room', labelRu: 'Пустая комната с окнами', promptText: 'an empty sunlit room with large windows' },
      ],
      outdoor_urban: [
        { id: 'narrow_street', labelRu: 'Узкая европейская улица', promptText: 'a narrow old-European city street' },
        { id: 'modern_plaza', labelRu: 'Современная площадь', promptText: 'a modern city plaza' },
        { id: 'brutalist', labelRu: 'Брутализм', promptText: 'brutalist concrete architecture' },
        { id: 'neon_night', labelRu: 'Неоновая ночная улица', promptText: 'a neon-lit night street' },
        { id: 'rooftop', labelRu: 'Крыша', promptText: 'a city rooftop with skyline view' },
        { id: 'bridge', labelRu: 'Пешеходный мост', promptText: 'an urban pedestrian bridge' },
        { id: 'metro_station', labelRu: 'Метро', promptText: 'a contemporary metro station' },
      ],
      outdoor_nature: [
        { id: 'forest_path', labelRu: 'Тропа в лесу', promptText: 'a quiet forest path' },
        { id: 'open_field', labelRu: 'Поле', promptText: 'an open grassy field' },
        { id: 'mountain_vista', labelRu: 'Горы', promptText: 'a mountain vista' },
        { id: 'sandy_beach', labelRu: 'Песчаный пляж', promptText: 'a sandy beach' },
        { id: 'rocky_coast', labelRu: 'Скалистый берег', promptText: 'a rocky coastal landscape' },
        { id: 'wheat_field', labelRu: 'Пшеничное поле', promptText: 'a golden wheat field' },
        { id: 'lake_shore', labelRu: 'Берег озера', promptText: 'a calm lake shore' },
        { id: 'flower_garden', labelRu: 'Цветущий сад', promptText: 'a blooming garden' },
        { id: 'snow_forest', labelRu: 'Заснеженный лес', promptText: 'a snow-covered forest' },
      ],
    },
  },
  season: {
    label: 'Время года',
    required: true,
    kind: 'chips',
    options: [
      { id: 'spring', labelRu: 'Весна', promptText: 'spring' },
      { id: 'summer', labelRu: 'Лето', promptText: 'summer' },
      { id: 'autumn', labelRu: 'Осень', promptText: 'autumn' },
      { id: 'winter', labelRu: 'Зима', promptText: 'winter' },
    ],
  },
  timeOfDay: {
    label: 'Время суток',
    required: true,
    kind: 'chips',
    options: [
      { id: 'morning_soft', labelRu: 'Утренний мягкий свет', promptText: 'soft morning light' },
      { id: 'midday', labelRu: 'Яркий дневной', promptText: 'bright midday light' },
      { id: 'golden_hour', labelRu: 'Золотой час', promptText: 'golden hour lighting' },
      { id: 'blue_hour', labelRu: 'Синий час', promptText: 'blue hour twilight' },
      { id: 'overcast', labelRu: 'Облачно', promptText: 'soft overcast daylight', onlyOutdoor: true },
      { id: 'night', labelRu: 'Ночь', promptText: 'nighttime with ambient city light', onlyLocationTypes: ['outdoor_urban', 'indoor'] },
    ],
  },

  framing: {
    label: 'Крупность кадра',
    required: true,
    kind: 'chips',
    options: [
      { id: 'full_body', labelRu: 'Полный рост', promptText: 'full body shot' },
      { id: 'three_quarter', labelRu: 'По колено', promptText: 'three-quarter length shot' },
      { id: 'medium', labelRu: 'По пояс', promptText: 'medium shot, waist up' },
    ],
  },
  aspectRatio: {
    label: 'Соотношение сторон',
    required: true,
    kind: 'aspect',
    options: [
      { id: 'portrait_3_4', labelRu: '3:4', promptText: '3:4', w: 3, h: 4 },
      { id: 'portrait_2_3', labelRu: '2:3', promptText: '2:3', w: 2, h: 3 },
      { id: 'portrait_9_16', labelRu: '9:16', promptText: '9:16', w: 9, h: 16 },
      { id: 'square', labelRu: '1:1', promptText: '1:1', w: 1, h: 1 },
    ],
  },
};

// Структура секций для левой колонки
window.SECTIONS = [
  {
    id: 'inputs',
    title: 'Входные данные',
    caption: 'Что подаем на вход',
    steps: ['referenceTypes', 'productPhotoCount', 'modelPhotoCount'],
  },
  {
    id: 'model',
    title: 'Модель',
    caption: 'Кто носит одежду',
    steps: ['gender', 'ageGroup', 'ethnicity', 'skinColor', 'eyeColor', 'bodyType', 'hairLength', 'hairColor', 'facialHair', 'features', 'featuresOverride'],
  },
  {
    id: 'product',
    title: 'Продукт',
    caption: 'Что продаём',
    steps: ['productGender', 'productCategories', 'productDetails'],
  },
  {
    id: 'styling',
    title: 'Стайлинг',
    caption: 'Как носят',
    steps: ['fitNotes', 'supportingItems', 'customStyling'],
  },
  {
    id: 'scene',
    title: 'Локация и настроение',
    caption: 'Где и с каким вайбом',
    steps: ['moodReference', 'locationMode', 'locationType', 'locationSpecific', 'season', 'timeOfDay'],
  },
  {
    id: 'frame',
    title: 'Кадр',
    caption: 'Как снято',
    steps: ['framing', 'aspectRatio'],
  },
];

// Обязательные шаги для счётчика прогресса (обязательные при текущем каскаде)
window.REQUIRED_STEPS_BASE = [
  'gender', 'ageGroup',
  'productGender', 'productCategories',
  'moodReference', 'locationMode',
  'framing', 'aspectRatio',
];
